# 1. Database Configuration
# Use the EXTERNAL host here
spring.datasource.url=jdbc:postgresql://dpg-d5gbme7fte5s73fhe050-a.oregon-postgres.render.com/textile_hub_db_346i?sslmode=require

# Separate credentials
spring.datasource.username=textile_hub_db_346i_user
spring.datasource.password=vkshaMlBcXtAKkvmEU6vWWb1nzWN06xM

# 2. Driver & Hibernate Settings
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
