# 1. Database Configuration
# Use the EXTERNAL host here
spring.datasource.url=jdbc:postgresql://dpg-d5g8cnp4tr6s73e57rug-a.oregon-postgres.render.com:5432/textile_hub_db?sslmode=require

# Separate credentials
spring.datasource.username=textile_hub_db_user
spring.datasource.password=2O6E2pEauIDiF29UmH7CwUHLuygxYIk1

# 2. Driver & Hibernate Settings
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true