# 1. Database Configuration
<<<<<<< HEAD
# Replace 'your_database_name' with the actual name of your schema
spring.datasource.url=jdbc:mysql://localhost:3306/textile_store_db

# Separate credentials
spring.datasource.username=root
spring.datasource.password=root
=======
# Use the EXTERNAL host here
spring.datasource.url=jdbc:postgresql://dpg-d5gbme7fte5s73fhe050-a.oregon-postgres.render.com/textile_hub_db_346i?sslmode=require

# Separate credentials
spring.datasource.username=textile_hub_db_346i_user
spring.datasource.password=vkshaMlBcXtAKkvmEU6vWWb1nzWN06xM
>>>>>>> c05fea83eb9515f3576decf03b0b9ebfe8861651

# 2. Driver & Hibernate Settings
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
